'use strict';

exports.constants = {
  CREATE_USER: 'CREATE_USER',
  UPDATE_AVATAR_BY_USER_ID: 'UPDATE_AVATAR_BY_USER_ID',
  GET_ALL: 'GET_ALL',
  GET_ALL_LIMITED_WITH_OFFSET: 'GET_ALL_LIMITED_WITH_OFFSET',
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  GET_USER_BY_EMAIL: 'GET_USER_BY_EMAIL',
  FIND_USERS_LIMITED_FROM_OFFSET: 'FIND_USERS_LIMITED_FROM_OFFSET',
  FIND_USERS_REGEX_LIMITED_FROM_OFFSET: 'FIND_USERS_REGEX_LIMITED_FROM_OFFSET',
  DELETE_USER_BY_ID: 'DELETE_USER_BY_ID',
  CLEAR_TABLE: 'CLEAR_TABLE',
  DROP_TABLE: 'DROP_TABLE'
};