'use strict';

module.exports = {
  DEFAULT_PAGINATION_LIMIT: 10,
  DEFAULT_PAGINATION_OFFSET: 0,

  ERROR: 'An error occured',

  DATALIST_VIEW_USER: 'DATALIST_VIEW_USER',
  DATALIST_VIEW_VOTATIONS: 'DATALIST_VIEW_VOTATIONS'
};