'use strict';

module.exports =  {
  DATA_LIST_VOTATIONS_VIEW: 'DATA_LIST_VOTATIONS_VIEW',
  DATA_LIST_USER_VOTATIONS_VIEW: 'DATA_LIST_USER_VOTATIONS_VIEW',
  DATA_LIST_VOTATIONS_SEARCH_VIEW: 'DATA_LIST_VOTATIONS_SEARCH_VIEW',
  DATA_LIST_USERS_SEARCH_VIEW: 'DATA_LIST_USERS_SEARCH_VIEW',

  SET_CUR_VIEW: 'SET_CUR_VIEW',
  SET_CUR_VIEW_DATA: 'SET_CUR_VIEW_DATA',
  SET_CUR_QUERY_VALUE: 'SET_CUR_QUERY_VALUE',
  SENDING_PAGINATION_REQUEST: 'SENDING_PAGINATION_REQUEST',
  SENDING_SEARCH_REQUEST: 'SENDING_SEARCH_REQUEST',
  SET_PAGINATION_OFFSET: 'SET_PAGINATION_OFFSET'
}