'use strict';

module.exports = {
  SET_AUTH: 'SET_AUTH', 
  CHANGE_LOGIN_FORM: 'CHANGE_LOGIN_FORM', 
  SENDING_LOGIN_REQUEST: 'SENDING_LOGIN_REQUEST',
  SENDING_LOGOUT_REQUEST: 'SENDING_LOGOUT_REQUEST',
  SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',
  SET_LOGIN_FORM_VALID: 'SET_LOGIN_FORM_VALID',
  SET_LOGIN_FORM_ERROR_MESSAGES: 'SET_LOGIN_FORM_ERROR_MESSAGES'
}