'use strict';

const registerConstants = {
  CHANGE_REGISTER_FORM: 'CHANGE_REGISTER_FORM', 
  SENDING_REGISTER_REQUEST: 'SENDING_REGISTER_REQUEST',
  SET_REGISTER_ERROR: 'SET_REGISTER_ERROR',
  SET_REGISTER_FORM_VALID: 'SET_REGISTER_FORM_VALID',
  SET_REGISTER_FORM_ERROR_MESSAGES: 'SET_REGISTER_FORM_ERROR_MESSAGES'
}

export default registerConstants;