'use strict';

module.exports =  {
  CHANGE_USERS_SEARCH_BOX: 'CHANGE_USERS_SEARCH_BOX',
  CHANGE_VOTATIONS_SEARCH_BOX: 'CHANGE_VOTATIONS_SEARCH_BOX',
  CHANGE_VOTATIONS_FILTER: 'CHANGE_VOTATIONS_FILTER',
  
  SENDING_USERS_SEARCH_REQUEST: 'SENDING_USERS_SEARCH_REQUEST',
  SENDING_VOTATIONS_SEARCH_REQUEST: 'SENDING_VOTATIONS_SEARCH_REQUEST',

  SET_USERS_SEARCH_RESULT: 'SET_USERS_SEARCH_RESULT', 
  SET_VOTATIONS_SEARCH_RESULT: 'SET_VOTATIONS_SEARCH_RESULT'
} 