'use strict';

module.exports = {
  JOIN: 'JOIN', 
  INVITE: 'INVITE',
  SEND_VOTE: 'SEND_VOTE',
  SAVE_VOTATION: 'SAVE_VOTATION',

  UPDATE_PARTICIPANTS: 'UPDATE_PARTICIPANTS',
  ADD_USER: 'ADD_USER',
  REMOVE_USER: 'REMOVE_USER',
  ADD_VOTE: 'ADD_VOTE',
  CLOSE_VOTATION: 'CLOSE_VOTATION'
};