'use strict';

module.exports = {
  CHANGE_SEARCH_VOTATIONS_VALUE: 'CHANGE_SEARCH_VOTATIONS_VALUE',
  CHANGE_FILTER_VOTATIONS_VALUE: 'CHANGE_FILTER_VOTATIONS_VALUE',
  
  CHANGE_NV_STATE: 'CHANGE_NV_STATE',

  ALL: 'All',
  OWNER_ONLY: 'Owner',
  OWNER_PARTICIPATED: 'Participated'
}