'use strict';

module.exports = {
  CHANGE_SEARCH_VOTATIONS_VALUE: 'CHANGE_SEARCH_VOTATIONS_VALUE',
  CHANGE_FILTER_VOTATIONS_VALUE: 'CHANGE_FILTER_VOTATIONS_VALUE',
  
  CHANGE_NV_STATE_TITLE: 'CHANGE_NV_STATE_TITLE',
  CHANGE_NV_STATE_DESC: 'CHANGE_NV_STATE_DESC',
  SET_NV_PARTICIPANTS: 'SET_NV_PARTICIPANTS',

  ALL: 'All',
  OWNER_ONLY: 'Owner',
  OWNER_PARTICIPATED: 'Participated'
}