'use strict';

exports.constants = {
  CREATE_VOTE: 'CREATE_VOTE',
  GET_VOTES_BY_VOTATION_ID: 'GET_VOTES_BY_VOTATION_ID',
  GET_ALL: 'GET_ALL',
  CLEAR_TABLE: 'CLEAR_TABLE',
  DROP_TABLE: 'DROP_TABLE'
};