'use strict';

exports.constants = {
  CREATE_VOTATION: 'CREATE_VOTATION',
  GET_ALL: 'GET_ALL',
  GET_VOTATION_BY_ID: 'GET_VOTATION_BY_ID',
  GET_ALL_LIMITED_FROM_OFFSET: 'GET_ALL_LIMITED_FROM_OFFSET',
  FIND_VOTATIONS_LIMITED_FROM_OFFSET: 'FIND_VOTATIONS_LIMITED_FROM_OFFSET',
  GET_USER_VOTATIONS_LIMITED_FROM_OFFSET: 'GET_USER_VOTATIONS_LIMITED_FROM_OFFSET',
  DELETE_VOTATION_BY_ID: 'DELETE_VOTATION_BY_ID',
  CLEAR_TABLE: 'CLEAR_TABLE',
  DROP_TABLE: 'DROP_TABLE'
};